### ISSUE TITLE
Lua error for known weapon skills

### ISSUE THREAD

**Issue by sinkda** [cloudbells/FieldGuide#4]
This may be related to issue #2 but I get the following Lua error:

![image](https://user-images.githubusercontent.com/17501944/60019948-fc908c80-965c-11e9-8385-a54762fdde23.png)

This happens when I toggle the "known spells" on the weapons pane.   As an aside, I also know those weapons on my Priest but are shown when the known spells are unchecked.  Probably related to said Lua error.

**Comment by cloudbells** [comment]
Yup this is because Warriors annoyingly have 14 weapon skills they can know (all of them minus wands), and since there is only room for 13 spells currently (I plan to possibly be able to customize width and height), the 14:th one gets pushed down to paladin, and the rest bug out. This will be fixed right after Priest stuff is done.

**Comment by cloudbells** [comment]
Could you check if there are errors now?
